name: Build and deploy on commit

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

    workflow_dispatch:

jobs:
    build:
        name: Build and deploy application to GitHub pages
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout the code
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 21
                  registry-url: https://registry.npmjs.org/

            - name: Clean install npm packages
              run: npm ci

            - name: Build
              run: npm run build

            - name: Deploy built application to GitHub pages
              if: github.event_name == 'push'
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
