name: Build and deploy on commit

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        name: Build application
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Clean install npm packages
              run: npm ci

            - name: Test
              run: npm test

            - name: Build
              run: npm run build

            - name: Upload Pages artifact
              if: github.event_name == 'push'
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./dist

    deploy:
        name: Deploy to GitHub Pages
        needs: build
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy
              uses: actions/deploy-pages@v4
              id: deployment
