name: Build and deploy on commit

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        name: Build application
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: Setup Node
              uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version: 22

            - name: Clean install npm packages
              run: npm ci

            - name: Test
              run: npm test

            - name: Build
              run: npm run build

            - name: Upload Pages artifact
              if: github.event_name == 'push'
              uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
              with:
                  path: ./dist

    deploy:
        name: Deploy to GitHub Pages
        needs: build
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy
              uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
              id: deployment
